import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { logo2 } from '@/assets'
import Link from 'next/link'
import { Loader,Header,Wrapper,Card,FormField } from '@/components'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [loading,setLoading] = useState<boolean>(false)
  const [allPosts,setAllPosts] = useState<null | any[]>(null)
  const [searchText, setSearchText] = useState<string>('')

  const RenderCards = ({data, title}:any) : JSX.Element => {
    try{
      if(data?.length > 0) return data.map((post: any,index: number) => <Card key={`cardWithIndex${index}`} {...post} /> )
      return <h2 className='mt-5 font-bold text-[#6469ff] text-xl uppercase'>{title}</h2>
    }catch(e: unknown){
      return <h2 className='mt-5 font-bold text-[#6469ff] text-xl uppercase'>Noting found</h2>
    }
  }
  return (
    <div className="app">
    <Head>
        <title>DALL-E</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Wrapper>
        <section className='max-w-7xl mx-auto'>
          <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>The community showcase</h1>
            <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Random text here</p>
          </div>
          <div className='mt-16'>
            <FormField />
          </div>
          <div className='mt-10'>
            {
              loading ? (
                <div className='flex justify-center items-center'>
                  <Loader />
                </div>
              ) :
              <>
                {
                searchText && <h1 className='font-medium text-[#666e75] text-xl mb-3'>
                  Showing results for <span className='text-[#222328]'>{searchText}</span>
                  </h1>
                }
                <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                  {
                    searchText ? (
                      <RenderCards data= {[]} title='No results found' />
                    ) : (
                      <RenderCards data = {[]} title='No post found' />
                    )
                  }
                </div>
              </>
            }
          </div>
        </section>
      </Wrapper>
    </div>
  )
}
